// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// Plugin is the predicate function for plugin builders.
type Plugin func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Storage is the predicate function for storage builders.
type Storage func(*sql.Selector)
