###
GET http://localhost:4000/api/v1/projects
Accept: application/json

###
POST http://localhost:4000/api/v1/projects
Content-Type: application/json

{
  "Code": "UPP-N",
  "Name": "Имя проекта",
  "Description": "",
  "Type": "configuration"
}


###
POST http://localhost:4000/api/v1/projects/9f775f89-2a7d-47a0-81c7-da6a36304f28
Content-Type: application/json

{
  "Code": "UPP-N",
  "Name": "Имя проекта 222",
  "Description": "",
  "Type": "configuration"
}