// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/khorevaa/r2gitsync/internal/services/db/ent/predicate"
	"github.com/khorevaa/r2gitsync/internal/services/db/ent/storage"
	"github.com/khorevaa/r2gitsync/internal/services/db/ent/storagecommit"
)

// StorageCommitQuery is the builder for querying StorageCommit entities.
type StorageCommitQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.StorageCommit
	// eager-loading edges.
	withStorage *StorageQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StorageCommitQuery builder.
func (scq *StorageCommitQuery) Where(ps ...predicate.StorageCommit) *StorageCommitQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit adds a limit step to the query.
func (scq *StorageCommitQuery) Limit(limit int) *StorageCommitQuery {
	scq.limit = &limit
	return scq
}

// Offset adds an offset step to the query.
func (scq *StorageCommitQuery) Offset(offset int) *StorageCommitQuery {
	scq.offset = &offset
	return scq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scq *StorageCommitQuery) Unique(unique bool) *StorageCommitQuery {
	scq.unique = &unique
	return scq
}

// Order adds an order step to the query.
func (scq *StorageCommitQuery) Order(o ...OrderFunc) *StorageCommitQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// QueryStorage chains the current query on the "storage" edge.
func (scq *StorageCommitQuery) QueryStorage() *StorageQuery {
	query := &StorageQuery{config: scq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(storagecommit.Table, storagecommit.FieldID, selector),
			sqlgraph.To(storage.Table, storage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, storagecommit.StorageTable, storagecommit.StorageColumn),
		)
		fromU = sqlgraph.SetNeighbors(scq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StorageCommit entity from the query.
// Returns a *NotFoundError when no StorageCommit was found.
func (scq *StorageCommitQuery) First(ctx context.Context) (*StorageCommit, error) {
	nodes, err := scq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{storagecommit.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *StorageCommitQuery) FirstX(ctx context.Context) *StorageCommit {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StorageCommit ID from the query.
// Returns a *NotFoundError when no StorageCommit ID was found.
func (scq *StorageCommitQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{storagecommit.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *StorageCommitQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StorageCommit entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one StorageCommit entity is not found.
// Returns a *NotFoundError when no StorageCommit entities are found.
func (scq *StorageCommitQuery) Only(ctx context.Context) (*StorageCommit, error) {
	nodes, err := scq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{storagecommit.Label}
	default:
		return nil, &NotSingularError{storagecommit.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *StorageCommitQuery) OnlyX(ctx context.Context) *StorageCommit {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StorageCommit ID in the query.
// Returns a *NotSingularError when exactly one StorageCommit ID is not found.
// Returns a *NotFoundError when no entities are found.
func (scq *StorageCommitQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = &NotSingularError{storagecommit.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *StorageCommitQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StorageCommits.
func (scq *StorageCommitQuery) All(ctx context.Context) ([]*StorageCommit, error) {
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return scq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (scq *StorageCommitQuery) AllX(ctx context.Context) []*StorageCommit {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StorageCommit IDs.
func (scq *StorageCommitQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := scq.Select(storagecommit.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *StorageCommitQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *StorageCommitQuery) Count(ctx context.Context) (int, error) {
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return scq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (scq *StorageCommitQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *StorageCommitQuery) Exist(ctx context.Context) (bool, error) {
	if err := scq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return scq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *StorageCommitQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StorageCommitQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *StorageCommitQuery) Clone() *StorageCommitQuery {
	if scq == nil {
		return nil
	}
	return &StorageCommitQuery{
		config:      scq.config,
		limit:       scq.limit,
		offset:      scq.offset,
		order:       append([]OrderFunc{}, scq.order...),
		predicates:  append([]predicate.StorageCommit{}, scq.predicates...),
		withStorage: scq.withStorage.Clone(),
		// clone intermediate query.
		sql:  scq.sql.Clone(),
		path: scq.path,
	}
}

// WithStorage tells the query-builder to eager-load the nodes that are connected to
// the "storage" edge. The optional arguments are used to configure the query builder of the edge.
func (scq *StorageCommitQuery) WithStorage(opts ...func(*StorageQuery)) *StorageCommitQuery {
	query := &StorageQuery{config: scq.config}
	for _, opt := range opts {
		opt(query)
	}
	scq.withStorage = query
	return scq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StorageCommit.Query().
//		GroupBy(storagecommit.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (scq *StorageCommitQuery) GroupBy(field string, fields ...string) *StorageCommitGroupBy {
	group := &StorageCommitGroupBy{config: scq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return scq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.StorageCommit.Query().
//		Select(storagecommit.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (scq *StorageCommitQuery) Select(fields ...string) *StorageCommitSelect {
	scq.fields = append(scq.fields, fields...)
	return &StorageCommitSelect{StorageCommitQuery: scq}
}

func (scq *StorageCommitQuery) prepareQuery(ctx context.Context) error {
	for _, f := range scq.fields {
		if !storagecommit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *StorageCommitQuery) sqlAll(ctx context.Context) ([]*StorageCommit, error) {
	var (
		nodes       = []*StorageCommit{}
		withFKs     = scq.withFKs
		_spec       = scq.querySpec()
		loadedTypes = [1]bool{
			scq.withStorage != nil,
		}
	)
	if scq.withStorage != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, storagecommit.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &StorageCommit{config: scq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := scq.withStorage; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*StorageCommit)
		for i := range nodes {
			if nodes[i].storage_commit_storage == nil {
				continue
			}
			fk := *nodes[i].storage_commit_storage
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(storage.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "storage_commit_storage" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Storage = n
			}
		}
	}

	return nodes, nil
}

func (scq *StorageCommitQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	_spec.Node.Columns = scq.fields
	if len(scq.fields) > 0 {
		_spec.Unique = scq.unique != nil && *scq.unique
	}
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *StorageCommitQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := scq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (scq *StorageCommitQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   storagecommit.Table,
			Columns: storagecommit.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: storagecommit.FieldID,
			},
		},
		From:   scq.sql,
		Unique: true,
	}
	if unique := scq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := scq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storagecommit.FieldID)
		for i := range fields {
			if fields[i] != storagecommit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scq *StorageCommitQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(storagecommit.Table)
	columns := scq.fields
	if len(columns) == 0 {
		columns = storagecommit.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scq.unique != nil && *scq.unique {
		selector.Distinct()
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector)
	}
	if offset := scq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StorageCommitGroupBy is the group-by builder for StorageCommit entities.
type StorageCommitGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *StorageCommitGroupBy) Aggregate(fns ...AggregateFunc) *StorageCommitGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the group-by query and scans the result into the given value.
func (scgb *StorageCommitGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := scgb.path(ctx)
	if err != nil {
		return err
	}
	scgb.sql = query
	return scgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := scgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (scgb *StorageCommitGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(scgb.fields) > 1 {
		return nil, errors.New("ent: StorageCommitGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := scgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) StringsX(ctx context.Context) []string {
	v, err := scgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (scgb *StorageCommitGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = scgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = fmt.Errorf("ent: StorageCommitGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) StringX(ctx context.Context) string {
	v, err := scgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (scgb *StorageCommitGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(scgb.fields) > 1 {
		return nil, errors.New("ent: StorageCommitGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := scgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) IntsX(ctx context.Context) []int {
	v, err := scgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (scgb *StorageCommitGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = scgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = fmt.Errorf("ent: StorageCommitGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) IntX(ctx context.Context) int {
	v, err := scgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (scgb *StorageCommitGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(scgb.fields) > 1 {
		return nil, errors.New("ent: StorageCommitGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := scgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := scgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (scgb *StorageCommitGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = scgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = fmt.Errorf("ent: StorageCommitGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) Float64X(ctx context.Context) float64 {
	v, err := scgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (scgb *StorageCommitGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(scgb.fields) > 1 {
		return nil, errors.New("ent: StorageCommitGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := scgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := scgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (scgb *StorageCommitGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = scgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = fmt.Errorf("ent: StorageCommitGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (scgb *StorageCommitGroupBy) BoolX(ctx context.Context) bool {
	v, err := scgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (scgb *StorageCommitGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range scgb.fields {
		if !storagecommit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := scgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (scgb *StorageCommitGroupBy) sqlQuery() *sql.Selector {
	selector := scgb.sql.Select()
	aggregation := make([]string, 0, len(scgb.fns))
	for _, fn := range scgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(scgb.fields)+len(scgb.fns))
		for _, f := range scgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(scgb.fields...)...)
}

// StorageCommitSelect is the builder for selecting fields of StorageCommit entities.
type StorageCommitSelect struct {
	*StorageCommitQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (scs *StorageCommitSelect) Scan(ctx context.Context, v interface{}) error {
	if err := scs.prepareQuery(ctx); err != nil {
		return err
	}
	scs.sql = scs.StorageCommitQuery.sqlQuery(ctx)
	return scs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (scs *StorageCommitSelect) ScanX(ctx context.Context, v interface{}) {
	if err := scs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (scs *StorageCommitSelect) Strings(ctx context.Context) ([]string, error) {
	if len(scs.fields) > 1 {
		return nil, errors.New("ent: StorageCommitSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := scs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (scs *StorageCommitSelect) StringsX(ctx context.Context) []string {
	v, err := scs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (scs *StorageCommitSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = scs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = fmt.Errorf("ent: StorageCommitSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (scs *StorageCommitSelect) StringX(ctx context.Context) string {
	v, err := scs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (scs *StorageCommitSelect) Ints(ctx context.Context) ([]int, error) {
	if len(scs.fields) > 1 {
		return nil, errors.New("ent: StorageCommitSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := scs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (scs *StorageCommitSelect) IntsX(ctx context.Context) []int {
	v, err := scs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (scs *StorageCommitSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = scs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = fmt.Errorf("ent: StorageCommitSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (scs *StorageCommitSelect) IntX(ctx context.Context) int {
	v, err := scs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (scs *StorageCommitSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(scs.fields) > 1 {
		return nil, errors.New("ent: StorageCommitSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := scs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (scs *StorageCommitSelect) Float64sX(ctx context.Context) []float64 {
	v, err := scs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (scs *StorageCommitSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = scs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = fmt.Errorf("ent: StorageCommitSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (scs *StorageCommitSelect) Float64X(ctx context.Context) float64 {
	v, err := scs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (scs *StorageCommitSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(scs.fields) > 1 {
		return nil, errors.New("ent: StorageCommitSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := scs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (scs *StorageCommitSelect) BoolsX(ctx context.Context) []bool {
	v, err := scs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (scs *StorageCommitSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = scs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{storagecommit.Label}
	default:
		err = fmt.Errorf("ent: StorageCommitSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (scs *StorageCommitSelect) BoolX(ctx context.Context) bool {
	v, err := scs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (scs *StorageCommitSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := scs.sql.Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
