// Code generated by entc, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/khorevaa/r2gitsync/internal/services/db/plugin"
	"github.com/khorevaa/r2gitsync/internal/services/db/pluginversion"
)

// PluginVersion is the model entity for the PluginVersion schema.
type PluginVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Broken holds the value of the "broken" field.
	Broken bool `json:"broken,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PluginVersionQuery when eager-loading is set.
	Edges                 PluginVersionEdges `json:"edges"`
	plugin_version_plugin *uuid.UUID
}

// PluginVersionEdges holds the relations/edges for other nodes in the graph.
type PluginVersionEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PluginVersionEdges) PluginOrErr() (*Plugin, error) {
	if e.loadedTypes[0] {
		if e.Plugin == nil {
			// The edge plugin was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: plugin.Label}
		}
		return e.Plugin, nil
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginVersion) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case pluginversion.FieldBroken:
			values[i] = new(sql.NullBool)
		case pluginversion.FieldVersion, pluginversion.FieldDescription:
			values[i] = new(sql.NullString)
		case pluginversion.FieldCreatedAt, pluginversion.FieldUpdatedAt, pluginversion.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case pluginversion.FieldID:
			values[i] = new(uuid.UUID)
		case pluginversion.ForeignKeys[0]: // plugin_version_plugin
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type PluginVersion", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginVersion fields.
func (pv *PluginVersion) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pluginversion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pv.ID = *value
			}
		case pluginversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pv.CreatedAt = value.Time
			}
		case pluginversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pv.UpdatedAt = value.Time
			}
		case pluginversion.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				pv.DeletedAt = new(time.Time)
				*pv.DeletedAt = value.Time
			}
		case pluginversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				pv.Version = value.String
			}
		case pluginversion.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				pv.Description = value.String
			}
		case pluginversion.FieldBroken:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field broken", values[i])
			} else if value.Valid {
				pv.Broken = value.Bool
			}
		case pluginversion.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_version_plugin", values[i])
			} else if value.Valid {
				pv.plugin_version_plugin = new(uuid.UUID)
				*pv.plugin_version_plugin = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// QueryPlugin queries the "plugin" edge of the PluginVersion entity.
func (pv *PluginVersion) QueryPlugin() *PluginQuery {
	return (&PluginVersionClient{config: pv.config}).QueryPlugin(pv)
}

// Update returns a builder for updating this PluginVersion.
// Note that you need to call PluginVersion.Unwrap() before calling this method if this PluginVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (pv *PluginVersion) Update() *PluginVersionUpdateOne {
	return (&PluginVersionClient{config: pv.config}).UpdateOne(pv)
}

// Unwrap unwraps the PluginVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pv *PluginVersion) Unwrap() *PluginVersion {
	tx, ok := pv.config.driver.(*txDriver)
	if !ok {
		panic("db: PluginVersion is not a transactional entity")
	}
	pv.config.driver = tx.drv
	return pv
}

// String implements the fmt.Stringer.
func (pv *PluginVersion) String() string {
	var builder strings.Builder
	builder.WriteString("PluginVersion(")
	builder.WriteString(fmt.Sprintf("id=%v", pv.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(pv.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(pv.UpdatedAt.Format(time.ANSIC))
	if v := pv.DeletedAt; v != nil {
		builder.WriteString(", deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", version=")
	builder.WriteString(pv.Version)
	builder.WriteString(", description=")
	builder.WriteString(pv.Description)
	builder.WriteString(", broken=")
	builder.WriteString(fmt.Sprintf("%v", pv.Broken))
	builder.WriteByte(')')
	return builder.String()
}

// PluginVersions is a parsable slice of PluginVersion.
type PluginVersions []*PluginVersion

func (pv PluginVersions) config(cfg config) {
	for _i := range pv {
		pv[_i].config = cfg
	}
}
