package cmd

const (
	VersobeEnv         = "GITSYNC_VERSOBE R2GITSYNC_VERSOBE"
	V8VersionEnv       = "GITSYNC_V8_VERSION GITSYNC_V8VERSION"
	V8PathEnv          = "GITSYNC_V8_PATH"
	WorkDirEnv         = "R2GITSYNC_WORKDIR GITSYNC_WORKDIR"
	PluginsDirEnv      = "GITSYNC_PLUGINS_PATH GITSYNC_PLUGINS_DIR GITSYNC_PL_DIR"
	DisabledPluginsEnv = "R2GITSYNC_DISABLED_PLUGINS"
	EnabledPluginsEnv  = "R2GITSYNC_ENABLED_PLUGINS"
)
