package cmd

const (
	Versobe     = "GITSYNC_VERSOBE R2GITSYNC_VERSOBE"
	V8Version   = "GITSYNC_V8_VERSION GITSYNC_V8VERSION"
	V8Path      = "GITSYNC_V8_PATH"
	WorkDir     = "R2GITSYNC_WORKDIR GITSYNC_WORKDIR"
	PLUGINS_DIR = "GITSYNC_PLUGINS_PATH GITSYNC_PLUGINS_DIR GITSYNC_PL_DIR"
)
